"""empty message

Revision ID: 1f0b3ed26d24
Revises: 60257290c730
Create Date: 2022-08-16 11:04:41.698205

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1f0b3ed26d24'
down_revision = '60257290c730'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'upcoming_shows')
    op.drop_column('artists', 'past_shows')
    op.add_column('shows', sa.Column('upcoming_shows', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('shows', sa.Column('past_shows', sa.ARRAY(sa.Integer()), nullable=True))
    op.drop_column('venues', 'upcoming_shows')
    op.drop_column('venues', 'past_shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('past_shows', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.add_column('venues', sa.Column('upcoming_shows', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.drop_column('shows', 'past_shows')
    op.drop_column('shows', 'upcoming_shows')
    op.add_column('artists', sa.Column('past_shows', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.add_column('artists', sa.Column('upcoming_shows', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
