"""empty message

Revision ID: 60257290c730
Revises: bfc580063987
Create Date: 2022-08-16 10:38:51.308920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60257290c730'
down_revision = 'bfc580063987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('upcoming_shows', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('artists', sa.Column('past_shows', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'past_shows')
    op.drop_column('artists', 'upcoming_shows')
    # ### end Alembic commands ###
