"""empty message

Revision ID: bfc580063987
Revises: 1d7301ae967d
Create Date: 2022-08-16 10:37:33.104154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfc580063987'
down_revision = '1d7301ae967d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('upcoming_shows', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('venues', sa.Column('past_shows', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'past_shows')
    op.drop_column('venues', 'upcoming_shows')
    # ### end Alembic commands ###
